### ISSUE TITLE
New tasks - Wishlist

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-go#28]
Are there any tasks you are missing. 

Here are some ideas of what I'd like to add:
- [ ] Usage of [webpack](https://webpack.github.io/)
- [ ] [postcss](http://postcss.org/) 
- [ ] Developing extensions in es6 and using [babel](https://babeljs.io/)
- [ ] Developing extensions in TypeScript
- [x] CleanCss task

Please feel free to add your wishes and vote for the existing proposals!

**Comment by Marnnn** [comment]
Love the idea of es6 and babel. I am trying to use Await in an extension so I can read an app variable which gives me a version number, I then want to load a specific version of an extension (module) based on this variable and return its definition and controller etc. Currently I'm still getting a pending promise when the paint function runs.
