### ISSUE TITLE
yml broken link

### ISSUE THREAD

**Issue by aalteirac** [stefanwalther/sense-go#29]
https://github.com/stefanwalther/sense-go/blob/master/src/default-config.yml is missing. I guess it's the root cause of :
[10:01:17] .: STARTING SENSE-GO :.
[10:01:17] Using the default sense-go settings ...
[10:01:17] Validation: one or more error occurred:
[10:01:17]   - packageName cannot be null or empty.
[10:01:17] AssertionError Task never defined: default

**Comment by stefanwalther** [comment]
This indicates that one of the following two is missing:
- Either you need to have a package.json in the root of your project including the property `name` (this will be taken with the lowest priority)
- Or you have a `.sense-go.yml file` and the property `packageName` there which will be taken then

**Comment by stefanwalther** [comment]
@aalteirac As a good starting point use https://github.com/stefanwalther/generator-sense-extension (but use the development branch v0.3.0) ... currently updating a lot there, but that should be a good start.
The idea is that the generator and sense-go play well together ...

**Comment by aalteirac** [comment]
Thanks ! Will use that for the skeleton, my package.json was definitely wrong ;-)

**Comment by stefanwalther** [comment]
Just realized another thing: The message "Using the default sense-go settings" indicates that you don't have neither a package.json nor a .sense-go.yml file, so the message can be improved to be more self-explanatory.
